config/routes.rb
NoCms::Admin::News::Engine.routes.draw do
  resources :items
  resources :categories
end

app/controllers/no_cms/admin/news/application_controller.rb
module NoCms
  module Admin
    module News
      class ApplicationController < NoCms::Admin::ApplicationController
      end
    end
  end
end

app/controllers/no_cms/admin/news/categories_controller.rb
require_dependency "no_cms/admin/news/application_controller"

module NoCms::Admin::News
  class CategoriesController < ApplicationController

    before_filter :load_menu_section
    before_filter :load_category, only: [:edit, :update, :destroy]
    before_filter :load_sidebar, only: [:index, :new, :edit]


    def new
      @category = NoCms::News::Category.new
    end

    def create
      @category = NoCms::News::Category.new category_params
      if @category.save
        @nocms_logger.info(I18n.t('.no_cms.admin.news.categories.create.success', title: @category.title), true)
        redirect_to edit_category_path(@category)
      else
        @nocms_logger.error(I18n.t('.no_cms.admin.news.categories.create.error', title: @category.title))
        load_sidebar
        render :new
      end
    end

    def edit
      @nocms_logger.add_message :news, I18n.t('.no_cms.admin.news.categories.edit.log_messages', title: @category.title)
    end

    def update
      if @category.update_attributes category_params
        @nocms_logger.info(I18n.t('.no_cms.admin.news.categories.update.success', title: @category.title), true)
        redirect_to edit_category_path(@category)
      else
        @nocms_logger.error(I18n.t('.no_cms.admin.news.categories.update.error', title: @category.title))
        load_sidebar
        render :edit
      end
    end

    def destroy
      if @category.destroy
        @nocms_logger.info(I18n.t('.no_cms.admin.news.categories.destroy.success', title: @category.title), true)
      else
        @nocms_logger.error(I18n.t('.no_cms.admin.news.categories.destroy.error', title: @category.title), true)
      end
      redirect_to categories_path
    end

    private

    def load_menu_section
      @current_section = 'categories'
    end

    def load_category
      @category = NoCms::News::Category.find(params[:id])
    end

    def load_sidebar
      @categories = NoCms::News::Category.all
    end

    def category_params
      params.require(:category).permit(:title)
    end

  end
end

app/controllers/no_cms/admin/news/items_controller.rb
require_dependency "no_cms/admin/news/application_controller"

module NoCms::Admin::News
  class ItemsController < ApplicationController

    before_filter :load_menu_section
    before_filter :load_item, only: [:edit, :update, :destroy]
    before_filter :load_sidebar, only: [:index, :new, :edit]


    def new
      @item = NoCms::News::Item.new
    end

    def create
      @item = NoCms::News::Item.new item_params
      if @item.save
        @nocms_logger.info(I18n.t('.no_cms.admin.news.items.create.success', title: @item.title), true)
        redirect_to edit_item_path(@item)
      else
        @nocms_logger.error(I18n.t('.no_cms.admin.news.items.create.error', title: @item.title))
        load_sidebar
        render :new
      end
    end

    def edit
      @nocms_logger.add_message :news, I18n.t('.no_cms.admin.news.items.edit.log_messages', title: @item.title)
    end

    def update
      if @item.update_attributes item_params
        @nocms_logger.info(I18n.t('.no_cms.admin.news.items.update.success', title: @item.title), true)
        redirect_to edit_item_path(@item)
      else
        @nocms_logger.error(I18n.t('.no_cms.admin.news.items.update.error', title: @item.title))
        load_sidebar
        render :edit
      end
    end

    def destroy
      if @item.destroy
        @nocms_logger.info(I18n.t('.no_cms.admin.news.items.destroy.success', title: @item.title), true)
      else
        @nocms_logger.error(I18n.t('.no_cms.admin.news.items.destroy.error', title: @item.title), true)
      end
      redirect_to items_path
    end

    private

    def load_menu_section
      @current_section = 'items'
    end

    def load_item
      @item = NoCms::News::Item.friendly.find(params[:id])
    end

    def load_sidebar
      @items = NoCms::News::Item.all
    end

    def item_params
      item_params = params.require(:item).permit(:title, :body, :slug, :published_at, :draft, category_ids: [])
      item_params.delete :slug unless item_params[:slug].blank?
      item_params
    end

  end
end

app/helpers/no_cms/admin/news/application_helper.rb
module NoCms
  module Admin
    module News
      module ApplicationHelper
      end
    end
  end
end

app/helpers/no_cms/admin/news/categories_helper.rb
module NoCms
  module Admin
    module News
      module CategoriesHelper
        def category_listing_item_classes item, current
          classes = []
          classes << 'current' if current == item
          classes
        end
      end
    end
  end
end

app/helpers/no_cms/admin/news/items_helper.rb
module NoCms
  module Admin
    module News
      module ItemsHelper
        def item_listing_item_classes item, current
          classes = []
          classes << 'current' if current == item
          classes << 'oculto' if item.draft
          classes
        end
      end
    end
  end
end

app/views/no_cms/admin/news/categories/_category_listing.html.erb
<ul>
  <%= yield %>
</ul>

app/views/no_cms/admin/news/categories/_category_listing_item.html.erb
<% current ||= nil %>
<li <%= raw "class='#{category_listing_item_classes(category, current).join(' ')}'"%>>
  <%= link_to category.title, edit_category_path(category)%>
  <div class="mo">
    <%= button_to '', category_path(category), method: :delete, class: "ico-mini-delete", title: t('.destroy') %>
  </div>
</li>

app/views/no_cms/admin/news/categories/_content_fields.html.erb
<div id="content_fields">
  <div class="row">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
</div>

app/views/no_cms/admin/news/categories/_toolbar_right.html.erb
<%= f.submit t('.submit'), name: :submit, class: "btn right" %>

app/views/no_cms/admin/news/categories/edit.html.erb
<% content_for :second_menu do %>
  <%= render partial: 'category_listing_item', collection: @categories, as: 'category', layout: 'category_listing', locals: { current: @category } unless @categories.blank? %>
<% end %>


<%= no_cms_admin_form_for @category do |f| %>
  <%= render partial: 'no_cms/admin/shared/toolbar', locals: { f: f } %>
  <div class="content">
    <%= render 'no_cms/admin/shared/log_messages' %>
    <%= render 'content_fields', f: f %>
  </div>
<% end %>

app/views/no_cms/admin/news/categories/index.html.erb
<% content_for :second_menu do %>
  <%= render partial: 'category_listing_item', collection: @categories, as: 'category', layout: 'category_listing' unless @categories.blank? %>
<% end %>


<div class="content">
  <%= render 'no_cms/admin/shared/log_messages' %>
</div>

app/views/no_cms/admin/news/categories/new.html.erb
<% content_for :second_menu do %>
  <%= render partial: 'category_listing_item', collection: @categories, as: 'category', layout: 'category_listing'  unless @categories.blank? %>
<% end %>


<%= no_cms_admin_form_for @category do |f| %>
  <%= render partial: 'no_cms/admin/shared/toolbar', locals: { f: f } %>
  <div class="content">
    <%= render 'no_cms/admin/shared/log_messages' %>
    <%= render 'content_fields', f: f %>
  </div>
<% end %>

app/views/no_cms/admin/news/items/_content_fields.html.erb
<div id="content_fields">
  <div class="row">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="row">
    <%= f.label_with_tooltip :slug, { tooltip: t('.slug_tooltip', base: no_cms_news.items_path)} %>
    <%= f.text_field :slug %>
  </div>

  <div class="row">
    <%= f.label_with_tooltip :published_at, { tooltip: t('.published_at_tooltip')} %>
    <%= f.datetime_picker :published_at %>
  </div>

  <div class="row">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="row">
    <%= f.label :category_ids %>
    <%= f.collection_select :category_ids, NoCms::News::Category.includes(:translations), :id, :title, {}, multiple: true %>
  </div>
</div>

app/views/no_cms/admin/news/items/_filter.html.erb
<form action="#">
  <div class="row">
    <label for="nombre">Nombre</label>
    <input type="text" name="nombre" id="" placeholder="Placeholder de nombre">
  </div>
  <div class="row">
    <label for="codigo-GG">Código GG</label>
    <input type="text" name="codigo-GG" id="">
  </div>
  <div class="row">
    <label for="ISBN">ISBN</label>
    <input type="text" name="ISBN" id="">
  </div>
  <div class="row">
    <label for="categoria">Categoría</label>
    <input type="text" name="categoria" id="">
  </div>
  <div class="row">
    <label for="xxx">Dos inputs en una sola línea</label>
    <input type="text" name="Nombre" id="" class="half">
    <input type="text" name="Apellidos" id="" class="half">
  </div>
  <div class="row">
    <label for="editorial">Editorial</label>
    <select name="editorial" id="">
      <option value="">Editorial 1</option>
      <option value="">Editorial 2</option>
      <option value="">Editorial 3</option>
    </select>
  </div>
  <div class="row">
    <label for="coleccion">Colección y país</label>
    <select name="coleccion" id="">
      <option value="">Sleccione colección</option>
      <option value="">Colección 1</option>
      <option value="">Colección 2</option>
      <option value="">Colección 3</option>
    </select>
    <select name="pais" id="">
      <option value="">Sleccione país</option>
      <option value="">Colección 1</option>
      <option value="">Colección 2</option>
      <option value="">Colección 3</option>
    </select>
  </div>
  <div class="row">
    <fieldset>
      <legend>Título del grupos de checkboxes</legend>
      <label><input type="checkbox" name="" id=""> Checkbox 1</label>
      <label><input type="checkbox" name="" id=""> Checkbox 2</label>
      <label><input type="checkbox" name="" id=""> Checkbox 4</label>
      <label><input type="checkbox" name="" id=""> Checkbox 5</label>
    </fieldset>
  </div>
  <div class="row filter-actions">
    <input type="submit" value="Filtrar" class="btn right">
    <input type="reset" value="Eliminar filtro" class="btn right">
  </div>
</form>

app/views/no_cms/admin/news/items/_item_listing.html.erb
<ul>
  <%= yield %>
</ul>

app/views/no_cms/admin/news/items/_item_listing_item.html.erb
<% current ||= nil %>
<li <%= raw "class='#{item_listing_item_classes(item, current).join(' ')}'"%>>
  <%= link_to item.title, edit_item_path(item)%>
  <div class="mo">
    <%= button_to '', item_path(item), method: :delete, class: "ico-mini-delete", title: t('.destroy') %>
    <%= button_to item_path(item), method: :put, class: "ico-mini-show-hide", title: (item.draft ? t('.show') : t('.hide')) do %>
      <% fields_for item do |f| %>
        <%= f.hidden_field :draft, value: (item.draft ? "0" : "1") %>
      <% end %>
    <% end %>
  </div>
</li>

app/views/no_cms/admin/news/items/_search.html.erb
<form action="#">
  <input type="text" name="serch" id="search-terms" placeholder="Search in this section">
  <input type="submit" value="" class="btn mini-search ">
</form>

app/views/no_cms/admin/news/items/_toolbar_right.html.erb
<%= f.submit t('.submit'), name: :submit, class: "btn right" %>
<% # We must check that routes are mounted. Otherwise it will get a 404 error %>
<%= link_to t('.visit'), no_cms_news.url_for(@item), target: '_blank', class: "preview btn right" if defined?(no_cms_news) && !@item.new_record?  %>

app/views/no_cms/admin/news/items/edit.html.erb
<% content_for :second_menu do %>
  <%= render partial: 'item_listing_item', collection: @items, as: 'item', layout: 'item_listing', locals: { current: @item } unless @items.blank? %>
<% end %>


<%= no_cms_admin_form_for @item do |f| %>
  <%= render partial: 'no_cms/admin/shared/toolbar', locals: { f: f } %>
  <div class="content">
    <%= render 'no_cms/admin/shared/log_messages' %>
    <%= render 'content_fields', f: f %>
  </div>
<% end %>

app/views/no_cms/admin/news/items/index.html.erb
<% content_for :second_menu do %>
  <%= render partial: 'item_listing_item', collection: @items, as: 'item', layout: 'item_listing' unless @items.blank? %>
<% end %>

<div class="content">
  <%= render 'no_cms/admin/shared/log_messages' %>
</div>

app/views/no_cms/admin/news/items/new.html.erb
<% content_for :second_menu do %>
  <%= render partial: 'item_listing_item', collection: @items, as: 'item', layout: 'item_listing' unless @items.blank? %>
<% end %>


<%= no_cms_admin_form_for @item do |f| %>
  <%= render partial: 'no_cms/admin/shared/toolbar', locals: { f: f } %>
  <div class="content">
    <%= render 'no_cms/admin/shared/log_messages' %>
    <%= render 'content_fields', f: f %>
  </div>
<% end %>